server:
  port: 8083
  forward-headers-strategy: framework
spring:
  application:
    name: task-ms
  data:
    mongodb:
      uri: mongodb+srv://bassem:bassem@authentication.6mvbj9d.mongodb.net/?retryWrites=true&w=majority
      database: tasks
      auto-index-creation: true
  main:
    allow-circular-references: true
  banner:
    location : classpath:banner.txt
  profiles:
    active: native
eureka:
  client:
    service-url:
      defaultZone: http://172.20.0.10:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
management:
  info:
    env:
      enabled: true

springdoc:
  swagger-ui:
    path: /docs
